### PR TITLE
Add LauchPad Playground to  Miscellaneous list

### PR DESCRIPTION
**Pull request by Juniorlimaivd**
Here is a Playground that i did recently and that i think will be useful to other people use as a interactive experience with music and to improve in programming.

### CODE REVIEW

**Comment by uraimo** [comment]
Hi, can you also increment the playground counter at the top of the file (`![123 playgrounds]`) to 124 and add your project as a submodule?

This should be enough:

```
mkdir playgrounds/Juniorlimaivd
cd playgrounds/Juniorlimaivd
git submodule add https://github.com/Juniorlimaivd/LaunchPad-Playground.git
```

**Comment by uraimo** [comment]
Oh, and add the ☘️ at the end of your description since it's written in Swift 3.

**Comment by Juniorlimaivd** [comment]
Done!

**Comment by uraimo** [comment]
Thanks! 👍

**Pull request merged**
