### PR TITLE
Added a new project for exploring SpriteKit collisions.

### PR DESCRIPTION
**Pull request by MacMeDan**
Added a new project for exploring SpriteKit collisions. I want to know what you think, I put it under the "SpriteKit" category but added a subcategory of "updated to swift 3". I'm Happy to change it around.

### CODE REVIEW

**Comment by uraimo** [comment]
Hi Dan, the category is ok and it could be worth adding a new tag that identifies Swift 3 playgrounds. Can you modify your PR to add a ☘  emoji at the end of your description?

**Comment by MacMeDan** [comment]
Ya for sure.

**Comment by MacMeDan** [comment]
I put it up in the key also.

**Comment by uraimo** [comment]
Merged, thanks!

**Pull request merged**
